### ISSUE TITLE
Wrong now day

### ISSUE THREAD

**Issue by Sergionius** [FabioFiuza/scrollable_clean_calendar#1]
Hello, thank you for great package, but I saw 2 issues, first of all I run example and start date is 28 Tuesday, but today is 27 Tuesday(see screenshots). Second: how can I set start week from Monday ? 
![IMG_7113](https://user-images.githubusercontent.com/10280032/97323737-29246c00-1882-11eb-8286-04bc4a64b1b4.PNG)
![IMG_7114](https://user-images.githubusercontent.com/10280032/97323743-2a559900-1882-11eb-873d-3215f62f285a.jpg)

**Comment by FabioFiuza** [comment]
Hi man. Thank you for the issue. I will verify it.

**Comment by fpizzicol** [comment]
@Sergionius thanks for your feedback, We've updated this lib to allow you to change the default start day of the week. We'll be working on the bug you reported and ASAP, we will release the bux fix with both corrections.

**Comment by FabioFiuza** [comment]
@Sergionius new version 0.1.1 start the week on Monday and fix the bug the order day. The new versions will parameterize. Thanks for the feedback.
