### ISSUE TITLE
_buildMonthLabelRow should concatenate two date formats to be valid for all locales

### ISSUE THREAD

**Issue by romannowicki** [FabioFiuza/scrollable_clean_calendar#16]
_buildMonthLabelRow should concatenate two date formats to be valid for all locales:

https://github.com/FabioFiuza/scrollable_clean_calendar/blob/e7f0473fd7c2ce7567ee090b1011a89a41d24af9/lib/scrollable_clean_calendar.dart#L329-L333

should be: 

`
DateFormat('MMMM', widget.locale).format(DateTime(month.year, month.month)).capitalize() + ' ' + DateFormat('yyyy', widget.locale).format(DateTime(month.year, month.month))
`

otherwise when language has more complex variation by cases it will display inappropriate value.

eg. `October 2021` in Polish is currently displayed as `Października 2021` and it should be `Październik 2021`

**Comment by rodrigodobbin** [comment]
Just one comment is that I used, template Strings insteado of Concatenation. CYA
