### ISSUE TITLE
Initial focus date

### ISSUE THREAD

**Issue by abc873693** [FabioFiuza/scrollable_clean_calendar#22]
Cloud add initial focus date ?
Like minimum date time is 2000.1.1, but i want focus on today in first time.

**Comment by rodrigodobbin** [comment]
When you mean focus, you are saying that the today should be already selected? Or that the screen should show the month that has today's date, even it there is previous months in the calendar? 

Cya

**Comment by abc873693** [comment]
I mean tha the screen should show the month that has today's date, even it there is previous months in the calendar.

Thanks

**Comment by rodrigodobbin** [comment]
Okay, thanks for this ideia. 

I will put this on the roadmap of the package and it will problably be done soon.

Cya.

**Comment by adimshev** [comment]
+1

**Comment by paulhulatt** [comment]
+1

**Comment by rodrigodobbin** [comment]
It is being maintained @Helzio , sorry for the delay. But I'm really busy with work and my master degree. So it's been difficult to maintain the calendar up to date in realTime. 

When I got time I will check this for sure. Or If anyone wants to open a MR, it will help a lot. 

Sorry again, but I will try to do my best.

Cya Folks

**Comment by tatsuyuki25** [comment]
Any update for this issue?

**Comment by tatsuyuki25** [comment]
> 
@rodrigodobbin I'm push PR.

**Comment by rodrigodobbin** [comment]
Thanks a lot @tatsuyuki25 . 

@FabioFiuza and I just release the version 1.3.0 in pub.dev with your PR. I think tomorrow everebody should be able to update the package.
