### ISSUE TITLE
Init date

### ISSUE THREAD

**Issue by desmeit** [FabioFiuza/scrollable_clean_calendar#23]
How can I set the initial date and scroll to it?

If I have 

```
minDate: DateTime(2010, 10, 1),
maxDate: DateTime(2030, 3, 1),
```

how can I scroll to DateTime.now() ?
Maybe it could work with scrollController. But jumpTo is not working because the months have an individual height.
Do you have a minimal example how this can be done?

**Comment by rodrigodobbin** [comment]
Hi @desmeit we have another issue about this feature. #22 

We will try to make it work as soon as possible.

Thanks for your feedback. 

I'm closing this issue since it is duplicate.
