### ISSUE TITLE
Disable already booked dates

### ISSUE THREAD

**Issue by DholaSain** [FabioFiuza/scrollable_clean_calendar#26]
This package has very clean and simple beautiful implementations. i just need the feature to disable the dates which are already booked.

**Comment by mohamoha6200** [comment]
I think that's possible through the "dayBuilder" Callback which lets you customize day cells the way you want. you could use IgnorePointer widget to disable the tapping if you need.

**Comment by rodrigodobbin** [comment]
Hi @DholaSain, as @mohamoha6200 said. You are cappable of doing this with the **dayBuilder** parameter Callback. 

Thanks for using our Calendar. 

Cya.
