### ISSUE TITLE
How to disable scrool?

### ISSUE THREAD

**Issue by Flavio-Vieirastack** [FabioFiuza/scrollable_clean_calendar#31]
Hello good morning, how do I disable the calendar scrool? I would like to have only one calendar displayed on the screen. If you have an example even better. Thank you very much

**Comment by rodrigodobbin** [comment]
Hi @Flavio-Vieirastack , sorry not to answer before. 

This calendar was designed to be scrollable. And unfortunately I don't think it will be on our roadmap to disable it. 

Thanks for your question. 

Cya.
