### ISSUE TITLE
how to show only month in calendar?

### ISSUE THREAD

**Issue by Flavio-Vieirastack** [FabioFiuza/scrollable_clean_calendar#34]
Can you give me a tip on how to show only the name of the month? Instead of January 2022 I wanted to show only January

**Comment by rodrigodobbin** [comment]
Hello @Flavio-Vieirastack. 

You can use the parameter `monthBuilder` to build the Month Widget the way you want. As you can see in the picture below. 

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-06-24 at 10 39 01](https://user-images.githubusercontent.com/3811222/175548033-a22ab48b-7b3d-481f-870c-6e67a4d3eef9.png)

Here is the code example (with prints to see the log) . Remember the month variable is a String with the value MONTH YEAR.

![Captura de Tela 2022-06-24 às 10 39 30](https://user-images.githubusercontent.com/3811222/175548147-6cc786b5-6c5e-4909-8477-c5f4985dde88.png)
