### ISSUE TITLE
How to disabled days specific in calendar

### ISSUE THREAD

**Issue by Jcr12** [FabioFiuza/scrollable_clean_calendar#35]
Hi,

Can specific days after the current date be deactivated?

**Comment by rodrigodobbin** [comment]
Hello @Jcr12.

We don't have this by default. 

But we have a `dayBuilder` method that alows you to create a day Widget the way you want. But just so you know, with you use the `dayBuilder` method you will be overriding everything we do by default with the Day. 

So you will have to create all the styles, and all the logic to style your days like we did for weekends, minDate, maxDate. You will have to create your tap/click event. Everything we did in the file **day_widget.dart** this method override and you'll have to create it. 

So If you do this (your own dayBuilder logic) you can deactivate specific dates. 

Here is a Simple example using this method: 
![Captura de Tela 2022-06-24 às 10 59 51](https://user-images.githubusercontent.com/3811222/175551460-7cd352fd-e9f0-4fb8-8efa-a42ea03c4cbc.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-06-24 at 10 59 54](https://user-images.githubusercontent.com/3811222/175551476-c96a4dea-e404-4798-99dc-6cdc7fe77896.png)
